repos:
  - repo: local
    hooks:
      - id: sort-txt-file
        name: Sort text file alphabetically
        entry: bash -c 'sort -o blocked_domains.txt blocked_domains.txt'
        language: system
        files: blocked_domains\.txt$
      
      - id: sort-json-files
        name: Sort JSON files alphabetically
        entry: python3 scripts/sort_json.py
        language: system
        files: \.json$
        pass_filenames: true